### ISSUE TITLE
3DSlicer installation

### ISSUE THREAD

**Issue by jmhmd** [QIICR/DSC_Analysis#1]
Is there a standard way to install this module in 3DSlicer? I don't see it in the extension manager, and not sure if there is a build step or how that works. Any pointers would be very appreciated!

**Comment by fedorov** [comment]
I do notice the that the extension build is currently failing on all platforms, so that is the reason you do not see it in the extension manager: http://slicer.cdash.org/index.php?project=SlicerPreview&display=project&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=DSC

**Comment by jmhmd** [comment]
Ah I see, I was wondering if it was an old project. Do you know of any good open source MR perfusion software currently available?

**Comment by fedorov** [comment]
There's an active effort to put together one here: https://www.osipi.org/task-force-1-2/.

You are welcome to join or comment on how useful or not the current list is (it is linked at the bottom of that page).

**Comment by jmhmd** [comment]
Great thanks! This is very helpful.

**Comment by lassoan** [comment]
@fedorov The [build errors](https://slicer.cdash.org/viewBuildError.php?buildid=2254525) are due to ITK changes, which do not seem difficult to fix. Have you tried to fix it but run into problems, or did not even try because the extension is not relevant anymore, or just did not have time to investigate?

**Comment by fedorov** [comment]
Andras - no, I have not tried to fix those. I just have not been able to make time to investigate this. Given the very limited demand from the user community for this and few other extensions that did not survive the ITK changes, I am not sure this is worth the effort, so that didn't add to my motivation.

**Comment by fedorov** [comment]
Also to be noted, the group that originally contributed this extension (that was not me) does not seem to be interested in maintaining it.

**Comment by lassoan** [comment]
I had a look at the software inventory (https://docs.google.com/spreadsheets/d/e/2PACX-1vSOHrNIiWcwDD5BoHij1dpXKgEejtohqKF6KZQMZi3G6GzM_BP8xpuwRbjFFvDW9Q/pubhtml?gid=1031101549&single=true) and there is no other package like this. There are only 3 open-source DSC packages:
- Lupe: implemented in IDL (proprietary computation environment, not available on linux), GPL license
- MCcbv: discontinued
- Perfx: looks like a dead project (last updated 5 years ago), messy software environment (implemented in delphi, partially relies on FSL)

Compared to these, this extension is not in a bad shape and its last functional version (Slicer-4.10.x) had over 2000 downloads.

Have the authors abandoned it because the algorithm has serious limitations that it would be too much work to fix? Or because it is not an active area of research anymore (commercial tools are sufficient for clinical work and researchers are not interested)?

It would be good to know this, because with 1-2 hours of work this extension could be made to work again, but if there is no interest then it is not worth the effort.

**Comment by fedorov** [comment]
Andras, I can't speak for the authors and I don't want to guess their motivation. I can only observe they did not participate in the maintenance of their contribution.
